version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=django_crud
      - DB_USER=root
      - DB_PASSWORD=Simha
    networks:
      - my_networks

networks:
 my_networks:
   driver: bridge